services:
  db:
    image: mysql:8.4
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: okubo
      MYSQL_DATABASE: sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: okubo
    ports:
      - "33061:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: unless-stopped

volumes:
  mysql-data:
